### ISSUE TITLE
Cannot build the database 

### ISSUE THREAD

**Issue by drix00** [openmicroanalysis/pyxray#18]
I cannot build the database in developer mode after the commit 2d4f8f251703392b330db7c10e4268d6fbbb6c73 on a windows 10 computer with Python 3.6 (64-bit). This is the output I obtained

```
$ python setup.py build
running build
running build_py
No SQL database found
Building database: 0it [00:00, ?it/s]
```

I found "No SQL database found" in the data.py and it seem when this file is imported, it did not find the database and use the _EmptyDatabase and did not build the missing database later. I am not sure where to create the SQL database file (`data/pyxray.db`)

Thanks Hendrix

**Comment by ppinard** [comment]
Have you tried to run `pip install -e .` again? I think the entry points might have changed.

**Comment by drix00** [comment]
You are right I did not run `pip install -e .`. After running it and `python setup.py build` the database is build.
Thanks
