### ISSUE TITLE
Doc on readthedocs.org doesn't seem to be up to date

### ISSUE THREAD

**Issue by ppinard** [openmicroanalysis/pyxray#21]
The last build of the documentation is from more than a year ago: https://readthedocs.org/projects/pyxray/builds/. The release of latest version (1.7.0) should have triggered a new build

**Comment by drix00** [comment]
The Github webhook was not working for some reason. It is not clear why. I need to delete and create again the Github webhook on readtgedocs to make it work. Other projects have this problem last year, but no explanation why. I test with this commit 188ab3967f70d5cf0eb64df9461b773514bf10c9 and it build the doc on readthedocs.
