### ISSUE TITLE
Use inner join instead of Python code to extract data from SQL

### ISSUE THREAD

**Issue by ppinard** [openmicroanalysis/pyxray#6]
Much of the logic in `pyxray/sql/data.py` is performed using Python code. I think it could be simplified using SQL language directly and INNER JOIN.

**Comment by fingenerf** [comment]
I'm not quite sure how exactly you want to do this. Can you maybe give an example with one of the functions?

**Comment by ppinard** [comment]
Implemented in 1.1.0
